### ISSUE TITLE
core.exception.InvalidMemoryOperationError

### ISSUE THREAD

**Issue by zafer06** [SSPkrolik/smtp#1]
Hello,
I try using MailSender example and my code is run without problem but end program output I get core.exception.InvalidMemoryOperationError  message

```d
MailSender sender = new MailSender("mail.mynet.com", 25);

SmtpReply smtpCevap = sender.connect();
writeln(smtpCevap.message)
```

// Output
-helena.mynet.com.tr
250-PIPELINING
250 8BITMIME

core.exception.InvalidMemoryOperationError

**Comment by SSPkrolik** [comment]
Added `quit()` method to `MailSender` class.
