### ISSUE TITLE
Lack of SSLv2 is not detected properly

### ISSUE THREAD

**Issue by opticron** [SSPkrolik/smtp#2]
When attempting to compile with OpenSSL that lacks SSLv2 support, smtp fails to build because SSLv2 code is not excluded properly. The relevant code is in smtp/ssl.d in the switch statement in the SocketSSL constructor. Changing the version statement to key off of OPENSSL_NO_SSL2 does not fix the problem as that version is not defined. I'll poke at things in the mean time and I'm available to test patches if you have suggestions.

**Comment by SSPkrolik** [comment]
Added one more configuration: `ssl-no-ssl2` for smtp lib itself for no-ssl2 builds of the OpenSSL library.
