### ISSUE TITLE
receiveData does not wait for the whole response

### ISSUE THREAD

**Issue by opticron** [SSPkrolik/smtp#3]
When dealing with servers that have more than a minimal amount of lag, partial responses can be read (probably only on unencrypted sessions) which exposes all kinds of other bugs with this library. I hacked around this by putting the following at the beginning of receieData() in client.d:

import core.thread:Thread;
Thread.sleep(dur!"msecs"(100));

**Comment by SSPkrolik** [comment]
Fixed getResponse() method to receive full response
